<table>
    <tbody>
        <?php
            $username = $this->getInfo()->getAdditionalInformation("cashcloud_username");
            $currency = $this->getInfo()->getAdditionalInformation("cashcloud_currency");
        ?>
        <tr>
            <th><strong>CashCloud <?php echo $this->__("user")?>:</strong></th>
        </tr>
        <tr>
            <td><?php echo $this->escapeHtml($username)?></td>
        </tr>
        <tr>
            <th><strong><?php echo $this->__("Amount")?>:</strong></th>
        </tr>
        <tr>
            <td><?php echo $this->escapeHtml($currency)?>: <?php echo $this->getFormattedPrice() ?></td>
        </tr>
        <tr>
            <th><strong><?php echo $this->__("Reason")?>:</strong></th>
        </tr>
        <tr>
            <td><?php echo $this->escapeHtml($this->getReason()) ?></td>
        </tr>
    </tbody>
</table>

<?php echo $this->getChildHtml()?>
